name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # 允许写入仓库内容（包括创建 Releases）

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ["1.21"]
        include:
          - os: ubuntu-latest
            go-version: "1.21"
          - os: windows-latest
            go-version: "1.21"
          - os: macos-latest
            go-version: "1.21"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }} # 设置 Go 版本

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go executable for ${{ matrix.os }}
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }} \
          GOARCH=amd64 go build -o action-${{ matrix.os }} .
        shell: bash

      - name: List generated files
        run: |
          echo "Generated files:"
          ls -la  # 列出生成的文件，确认它们是否存在

      - name: Upload the executable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: action-${{ matrix.os }}-executable
          path: action-${{ matrix.os }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: action-${{ matrix.os }}-executable
          path: .

      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            action-ubuntu-latest
            action-windows-latest
            action-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
