name: Release

on:
  push:
    branches:
      - master # 确保推送到 master 分支触发工作流
    tags:
      - "v1.0.0"
permissions:
  contents: write # 允许写入仓库内容（包括创建 Releases）

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ["1.21"]
        include:
          - os: ubuntu-latest
            go-version: "1.21"
          - os: windows-latest
            go-version: "1.21"
          - os: macos-latest
            go-version: "1.21"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }} # 设置 Go 版本

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go executable for ${{ matrix.os }}
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }} \
          GOARCH=amd64 go build -o action-${{ matrix.os }} .
        shell: bash

      - name: List generated files
        run: |
          echo "Generated files:"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then powershell Rename-Item action-windows-latest action-windows-latest.exe&&dir; else ls -la; fi
        shell: bash

      - name: Upload the executable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: action-${{ matrix.os }}-executable # 上传对应平台的可执行文件
          path: action-${{ matrix.os }} # 上传文件

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download Ubuntu build artifact
        uses: actions/download-artifact@v3
        with:
          name: action-ubuntu-latest-executable # 下载 Ubuntu 工件
          path: .

      - name: Download macOS build artifact
        uses: actions/download-artifact@v3
        with:
          name: action-macos-latest-executable # 下载 macOS 工件
          path: .

      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            action-ubuntu-latest
            action-windows-latest.exe  # Windows 工件加上 .exe 后缀  
            action-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
