name: Go Build and Release

on:
  push:
    branches:
      - master # 只在 main 分支推送时触发
  pull_request:
    branches:
      - master # 只在 main 分支的 Pull Request 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21" # 设置 Go 版本

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go executable
        run: |
          go build -o action.exe .

      - name: Upload the executable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: action-executable
          path: action.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          files: action.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
